services:
  - type: web
    name: shiny-scheduler-app
    env: docker
    repo: https://github.com/YOUR_USERNAME/YOUR_REPO_NAME
    branch: main
    dockerfilePath: ./Dockerfile
    plan: free
    autoDeploy: true
