services:
  - type: web
    name: production-scheduler
    runtime: shiny
    env: r
    buildCommand: Rscript install_packages.R
    startCommand: R -e 'shiny::runApp("app.R", port = $PORT, host = "0.0.0.0")'
    envVars:
      - key: unlock_date
        value: "2026-04-25"
      - key: correct_password
        value: "1020304050"
