services:
  - type: web
    name: shiny-scheduler-app
    env: docker
    repo: https://github.com/mertbkatal/productionschedheuristicoptimizerTCI
    branch: main
    dockerfilePath: ./Dockerfile
    plan: free
    autoDeploy: true
